<a href="https://colab.research.google.com/github/Aakash50909/Cognitive-Computing-Assignments/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
#Question 1
a=np.array([1,2,3,4,5])
a+=2
print(a)
a-=2
a*=3
print(a)
a=a/3
a/=2
print(a)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [14]:
#Question 2
arr=np.array([1,2,3,6,4,5])
reverse_arr=np.flip(arr)
print(reverse_arr)
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
most_freq=np.bincount(x).argmax()
print(most_freq)
indices=np.where(x==most_freq)[0]
print(indices)
most_freq=np.bincount(y).argmax()
print(most_freq)
indices=np.where(y==most_freq)[0]#np.unique if two numbers clash
print(indices)


[5 4 6 3 2 1]
1
[0 5 7 8 9]
1
[0 1 2]


In [19]:
#Question 3
arr=np.array([[10, 20, 30],
             [40, 50, 60],
             [70, 80, 90]])
arr[0][1]
arr[2][0]

70

In [37]:
#Question 4
Aakash_Chandra=np.array(np.linspace(10,100,25))
print(Aakash_Chandra)
print("Dimensions:",Aakash_Chandra.ndim)
print("Shape:",Aakash_Chandra.shape)
print("Total Elements:",Aakash_Chandra.size)
print("Data Type:",Aakash_Chandra.dtype)
print("Total bytes consumed",Aakash_Chandra.nbytes)
print("Transpose Array:\n",Aakash_Chandra.reshape(-1,1))#COLUMN_VECTOR AS TRANSPOSE ASSUMED
print("Using T attribute:\n",Aakash_Chandra.T)#NotPossible FOR 1D

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total bytes consumed 200
Transpose Array:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [50]:
#Question 5
ucs420_Aakash=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420_Aakash)
print("Mean:",ucs420_Aakash.mean())
print("Median:",np.median(ucs420_Aakash))
print("Max:",ucs420_Aakash.max())
print("Min:",ucs420_Aakash.min())
print("Unique Elements:",np.unique(ucs420_Aakash))
reshaped_ucs420_Aakash=ucs420_Aakash.reshape(4,3)
resized_ucs420_Aakash=np.resize(ucs420_Aakash,(2,3))
print("Reshaped Array:\n",reshaped_ucs420_Aakash)
print("Resized Array:\n",resized_ucs420_Aakash)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array:
 [[10 20 30]
 [40 50 60]]
